staging: 
  :facebook:
    :api_key: '203402889721350'
    :secret_key: '9aa801d7ec4418a9bd81d3464a3078a0'

development:
  :facebook:
    :api_key: '190285970988638'
    :secret_key: 'a8859f030a6c7259a61b0a7aa1774742'
  :twitter:
    :api_key: 'qGccYRYVbwdH6tFlYah1Ng'
    :secret_key: 'vusGXcUm4GUGXq3qCOaKgjLNl0xulRB28Px0G3Bxrk'
  :linked_in:
    :api_key: 'a33rq3rqvlcs'
    :secret_key: 'x0JSZATLpG4uPkJQ'

production:
  :facebook:
    :api_key: '146470382109652'
    :secret_key: '2b4203b9025848b05258a2a5a9358191'
